//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coders.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coders.Strings.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error occurred while trying to get instance of type &apos;{0}&apos;..
        /// </summary>
        public static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type &apos;{0}&apos; or extension is not allowed. Valid extensions are: {1}.
        /// </summary>
        public static string AttachmentContentTypeNotValid {
            get {
                return ResourceManager.GetString("AttachmentContentTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must not be greater then {0}x{1} pixels..
        /// </summary>
        public static string AttachmentImageDimensionMaxNotValid {
            get {
                return ResourceManager.GetString("AttachmentImageDimensionMaxNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must be greater then {0}x{1} pixels..
        /// </summary>
        public static string AttachmentImageDimensionMinNotValid {
            get {
                return ResourceManager.GetString("AttachmentImageDimensionMinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size must not be greater than {0}..
        /// </summary>
        public static string AttachmentLengthNotValid {
            get {
                return ResourceManager.GetString("AttachmentLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains characters that are not valid. Valid characters are letters, numbers and spaces..
        /// </summary>
        public static string CharacterNotValid {
            get {
                return ResourceManager.GetString("CharacterNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is not valid. A valid example would be mm/dd/yyyy.
        /// </summary>
        public static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid a valid email address. A valid email address is &apos;name@example.com&apos;..
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not equal to or does not match {1}..
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, an error has occurred..
        /// </summary>
        public static string GenericMessage {
            get {
                return ResourceManager.GetString("GenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identity is null..
        /// </summary>
        public static string IdentityNull {
            get {
                return ResourceManager.GetString("IdentityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image type &apos;{0}&apos; is not allowed. Valid extensions are: {1}.
        /// </summary>
        public static string ImageContentTypeNotValid {
            get {
                return ResourceManager.GetString("ImageContentTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must not be greater then {0}x{1} pixels..
        /// </summary>
        public static string ImageDimensionMaxNotValid {
            get {
                return ResourceManager.GetString("ImageDimensionMaxNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must be greater then {0}x{1} pixels..
        /// </summary>
        public static string ImageDimensionMinNotValid {
            get {
                return ResourceManager.GetString("ImageDimensionMinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters..
        /// </summary>
        public static string LengthMin {
            get {
                return ResourceManager.GetString("LengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters and no longer then {2} characters..
        /// </summary>
        public static string LengthMinOrMax {
            get {
                return ResourceManager.GetString("LengthMinOrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit must be greater then zero..
        /// </summary>
        public static string LimitGreaterThanZero {
            get {
                return ResourceManager.GetString("LimitGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page must be greater then zero..
        /// </summary>
        public static string PageGreaterThanZero {
            get {
                return ResourceManager.GetString("PageGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not build the &apos;{0}&apos; path..
        /// </summary>
        public static string PathFailed {
            get {
                return ResourceManager.GetString("PathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;Session&apos; for argument &apos;context&apos; of type &apos;HttpContext&apos; is null..
        /// </summary>
        public static string SessionNull {
            get {
                return ResourceManager.GetString("SessionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting key has already been taken..
        /// </summary>
        public static string SettingKeyTaken {
            get {
                return ResourceManager.GetString("SettingKeyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total must be greater then or equal to zero..
        /// </summary>
        public static string TotalGreaterThanOrEqualZero {
            get {
                return ResourceManager.GetString("TotalGreaterThanOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address or password is incorrect..
        /// </summary>
        public static string UserAuthenticationFailed {
            get {
                return ResourceManager.GetString("UserAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;File&apos; for type &apos;UserAvatarCreate&apos; is null..
        /// </summary>
        public static string UserAvatarCreateFileNull {
            get {
                return ResourceManager.GetString("UserAvatarCreateFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not locate an account with this email address..
        /// </summary>
        public static string UserEmailAddressNotFound {
            get {
                return ResourceManager.GetString("UserEmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has already been used..
        /// </summary>
        public static string UserEmailAddressTaken {
            get {
                return ResourceManager.GetString("UserEmailAddressTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not locate an account with this name..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name has already been taken..
        /// </summary>
        public static string UserNameTaken {
            get {
                return ResourceManager.GetString("UserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is protected and cannot be modified except by the user..
        /// </summary>
        public static string UserProtected {
            get {
                return ResourceManager.GetString("UserProtected", resourceCulture);
            }
        }
    }
}
