//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coders.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coders.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment rule &apos;{0}&apos; for group &apos;{1}&apos; has been successfully created..
        /// </summary>
        public static string AttachmentRuleCreated {
            get {
                return ResourceManager.GetString("AttachmentRuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment rule &apos;{0}&apos; for group &apos;{1}&apos; has been successfully updated..
        /// </summary>
        public static string AttachmentRuleUpdated {
            get {
                return ResourceManager.GetString("AttachmentRuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment has been successfully updated..
        /// </summary>
        public static string AttachmentUpdated {
            get {
                return ResourceManager.GetString("AttachmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country &apos;{0}&apos; has been successfully created..
        /// </summary>
        public static string CountryCreated {
            get {
                return ResourceManager.GetString("CountryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string CountryUpdated {
            get {
                return ResourceManager.GetString("CountryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not authorized to access this page. This can happen if your account not have the proper privileges..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; has been successfully created..
        /// </summary>
        public static string SettingCreated {
            get {
                return ResourceManager.GetString("SettingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string SettingUpdated {
            get {
                return ResourceManager.GetString("SettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results {0} to {1} of {2}.
        /// </summary>
        public static string ShowingResults {
            get {
                return ResourceManager.GetString("ShowingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone {0}&apos; has been successfully created..
        /// </summary>
        public static string TimeZoneCreated {
            get {
                return ResourceManager.GetString("TimeZoneCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string TimeZoneUpdated {
            get {
                return ResourceManager.GetString("TimeZoneUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully created..
        /// </summary>
        public static string UserAccountCreated {
            get {
                return ResourceManager.GetString("UserAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully reset. We have sent you an email which contains your new password..
        /// </summary>
        public static string UserAccountPasswordReset {
            get {
                return ResourceManager.GetString("UserAccountPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences has been successfully updated..
        /// </summary>
        public static string UserAccountPreferenceUpdated {
            get {
                return ResourceManager.GetString("UserAccountPreferenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was successfully updated.
        /// </summary>
        public static string UserAccountUpdated {
            get {
                return ResourceManager.GetString("UserAccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ban for the user &apos;{0}&apos; has been successfully created..
        /// </summary>
        public static string UserBanCreated {
            get {
                return ResourceManager.GetString("UserBanCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ban for the user &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string UserBanUpdated {
            get {
                return ResourceManager.GetString("UserBanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; has been successfully created..
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully reset for the user &apos;{0}&apos;. We have sent the user an email which contains thier new password..
        /// </summary>
        public static string UserPasswordReset {
            get {
                return ResourceManager.GetString("UserPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The privileges for the user &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string UserPrivilegeUpdated {
            get {
                return ResourceManager.GetString("UserPrivilegeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &apos;{0}&apos; has been successfully created..
        /// </summary>
        public static string UserRoleCreated {
            get {
                return ResourceManager.GetString("UserRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string UserRoleUpdated {
            get {
                return ResourceManager.GetString("UserRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; has been successfully updated..
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
    }
}
