// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha1(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha1(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha256(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha256(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha384(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha384(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha512(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Md", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToMd5(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Md", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToMd5(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sha", Scope = "member", Target = "Coders.Extensions.HashExtension.#HashToSha512(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Coders.Extensions.StringExtension.#Slug(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Extensions.SpecificationExtension.#Or`1(System.Linq.Expressions.LambdaExpression,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Extensions.SpecificationExtension.#And`1(System.Linq.Expressions.LambdaExpression,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Specifications.Specification`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Specifications.Specification`1.#Predicate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Coders.Models.Users.IUserHostService.#GetAddress()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "int", Scope = "member", Target = "Coders.Extensions.ObjectExtension.#AsInt(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Users.UserSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Users.User,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Extensions.SpecificationExtension.#And`1(System.Linq.Expressions.LambdaExpression,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Extensions.SpecificationExtension.#Or`1(System.Linq.Expressions.LambdaExpression,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Coders.Models.Common.IAuthenticationService.#LogOnUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Coders.Models.Common.IAuthenticationService.#ReturnUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Settings.SettingSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Settings.Setting,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Specifications.Specification`1.#OrderBy`1(System.Linq.IQueryable`1<!0>,System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>,Coders.Models.Common.Enums.SortOrder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Specifications.ISpecification`1.#OrderBy`1(System.Linq.IQueryable`1<!0>,System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>,Coders.Models.Common.Enums.SortOrder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Coders.Models.EmailBase.#SiteUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Attachments.AttachmentRuleSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Attachments.AttachmentRule,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Countries.CountrySpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Countries.Country,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.TimeZones.TimeZoneSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.TimeZones.TimeZone,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Users.UserSearchSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Users.UserSearch,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Users.UserHostSearchSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Users.UserHostSearch,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Models.Users.UserBanSpecification.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<Coders.Models.Users.UserBan,System.Boolean>>)")]
