// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dsts", Scope = "member", Target = "Coders.Web.Models.UserCreate.#Dsts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Users.HomeController.#Update(Coders.Web.Models.UserUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectList`1(System.Collections.Generic.IList`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Int32>>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectList`1(System.Collections.Generic.IList`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Int32>>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.String>>,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectList`1(System.Collections.Generic.IList`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Int32>>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.String>>,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListLocalizedFor`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListLocalizedFor`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListTree`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListTree`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dsts", Scope = "member", Target = "Coders.Web.Models.Users.UserCreate.#Dsts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Users.HomeController.#Update(Coders.Web.Models.Users.UserUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Validators", Scope = "namespace", Target = "Coders.Web.Validators")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "helper", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListLocalized(System.Web.Mvc.HtmlHelper,System.String,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "helper", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListLocalizedFor`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "helper", Scope = "member", Target = "Coders.Web.Extensions.SelectExtension.#SelectListTree`2(System.Web.Mvc.HtmlHelper`1<!!0>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,!!1>>,System.Web.Mvc.SelectList)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Coders.Web.Widgets.WidgetBase.#Attributes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Coders.Web.Widgets.WidgetBase.#ViewData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Extensions.ValidatorExtension.#UserAuthorize`1(FluentValidation.IRuleBuilder`2<!!0,System.String>,System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Validators.UserAuthorizeValidator`1.#.ctor(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Coders.Web.Widgets.IWidget.#Attributes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Coders.Web.Extensions.DateExtension.#Past(System.DateTime,System.Security.Principal.IIdentity)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Administration.AttachmentRuleController.#Create(Coders.Web.Models.Attachments.AttachmentRuleCreateOrUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Administration.CountryController.#Create(Coders.Web.Models.Countries.CountryCreateOrUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Administration.SettingController.#Create(Coders.Web.Models.Settings.SettingCreateOrUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Administration.TimeZoneController.#Create(Coders.Web.Models.TimeZones.TimeZoneCreateOrUpdate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dsts", Scope = "member", Target = "Coders.Web.Models.Users.UserPreferenceUpdate.#Dsts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dsts", Scope = "member", Target = "Coders.Web.Models.Users.UserAdminUpdate.#Dsts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Coders.Web.Controllers.Users.Administration.HomeController.#Create(Coders.Web.Models.Users.UserAdminCreate)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Coders.Web.Filters.FilterBase.#Filters")]